/* Generated by build-data.cjs from the bundled game source. */
const EventData = {
  "version": "4.1.3.8",
  "tiers": {
    "Small": {
      "order": 1,
      "gather": 0.1,
      "process": 0.1,
      "dmg": 0.05,
      "xp": 0.1,
      "mins": 30
    },
    "Large": {
      "order": 2,
      "gather": 0.15,
      "process": 0.15,
      "dmg": 0.08,
      "xp": 0.15,
      "mins": 60
    },
    "Grand": {
      "order": 3,
      "gather": 0.2,
      "process": 0.2,
      "dmg": 0.12,
      "xp": 0.2,
      "mins": 120
    }
  },
  "tints": {
    "green": "hue-rotate(95deg) saturate(0.6) brightness(1.1) contrast(1.1) drop-shadow(0 0 5px rgba(168,85,247,0.85))",
    "purple": "sepia(1) hue-rotate(225deg) saturate(2.6) brightness(0.8) contrast(1.1) drop-shadow(0 0 5px rgba(74,222,128,0.8))",
    "boss": "hue-rotate(95deg) saturate(0.6) brightness(1.1) contrast(1.1) drop-shadow(0 0 4px rgba(239,68,68,0.95)) drop-shadow(0 0 10px rgba(168,85,247,0.7))"
  },
  "monsters": [
    {
      "id": "h_chicken",
      "name": "Haunted Chicken",
      "level": 5,
      "image": "combat_simulator/Assets/Monsters/verdantmeadows/chicken.png",
      "tint": "green",
      "drops": [
        {
          "item": "Small Gathering Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small Processing Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small Combat Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small XP Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "h_spider",
      "name": "Haunted Spider",
      "level": 20,
      "image": "combat_simulator/Assets/Monsters/forest/spider.png",
      "tint": "purple",
      "drops": [
        {
          "item": "Small Gathering Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small Processing Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small Combat Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small XP Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "h_chieftain",
      "name": "Haunted Chieftain",
      "level": 40,
      "image": "combat_simulator/Assets/Monsters/verdantmeadows/goblinchieftain.png",
      "tint": "green",
      "drops": [
        {
          "item": "Small Gathering Candy",
          "c": 0.03,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small Processing Candy",
          "c": 0.03,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small Combat Candy",
          "c": 0.03,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Small XP Candy",
          "c": 0.03,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "h_zombie",
      "name": "Haunted Zombie",
      "level": 60,
      "image": "combat_simulator/Assets/Monsters/dungeon/zombie.png",
      "tint": "purple",
      "drops": [
        {
          "item": "Large Gathering Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large Processing Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large Combat Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large XP Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "h_demon",
      "name": "Haunted Demon",
      "level": 80,
      "image": "combat_simulator/Assets/Monsters/dungeon/demon.png",
      "tint": "green",
      "drops": [
        {
          "item": "Large Gathering Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large Processing Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large Combat Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large XP Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "h_vampire",
      "name": "Haunted Vampire",
      "level": 100,
      "image": "combat_simulator/Assets/Monsters/dungeon/vampire.png",
      "tint": "purple",
      "drops": [
        {
          "item": "Large Gathering Candy",
          "c": 0.03,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large Processing Candy",
          "c": 0.03,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large Combat Candy",
          "c": 0.03,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Large XP Candy",
          "c": 0.03,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "h_tidewitch",
      "name": "Haunted Tidewitch",
      "level": 120,
      "image": "combat_simulator/Assets/Monsters/abyssal/tidewitch.png",
      "tint": "green",
      "drops": [
        {
          "item": "Grand Gathering Candy",
          "c": 0.02,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand Processing Candy",
          "c": 0.02,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand Combat Candy",
          "c": 0.02,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand XP Candy",
          "c": 0.02,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "h_lich",
      "name": "Haunted Lich",
      "level": 140,
      "image": "combat_simulator/Assets/Monsters/frostlands/frozenlich.png",
      "tint": "purple",
      "drops": [
        {
          "item": "Grand Gathering Candy",
          "c": 0.02,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand Processing Candy",
          "c": 0.02,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand Combat Candy",
          "c": 0.02,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand XP Candy",
          "c": 0.02,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "h_guardian",
      "name": "Haunted Guardian",
      "level": 165,
      "image": "combat_simulator/Assets/Monsters/ruins/ruinguardian.png",
      "tint": "green",
      "drops": [
        {
          "item": "Grand Gathering Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand Processing Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand Combat Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand XP Candy",
          "c": 0.025,
          "q": [
            1,
            1
          ]
        }
      ]
    },
    {
      "id": "haunted_boss",
      "name": "Haunted Relic Wraith",
      "level": 210,
      "image": "combat_simulator/Assets/Monsters/ruins/relicwraith.png",
      "tint": "boss",
      "drops": [
        {
          "item": "Grand Combat Candy",
          "c": 1,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand Gathering Candy",
          "c": 0.35,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand Processing Candy",
          "c": 0.35,
          "q": [
            1,
            1
          ]
        },
        {
          "item": "Grand XP Candy",
          "c": 0.35,
          "q": [
            1,
            1
          ]
        }
      ]
    }
  ],
  "blessings": [
    {
      "id": "favorable_winds",
      "name": "Favorable Winds",
      "level": 45,
      "luck": 0.08
    },
    {
      "id": "divination",
      "name": "Divination",
      "level": 92,
      "luck": 0.12
    },
    {
      "id": "ultimate_fortune",
      "name": "Ultimate Fortune",
      "level": 96,
      "luck": 0.25
    },
    {
      "id": "eternal_harvest",
      "name": "Eternal Harvest",
      "level": 107,
      "luck": 0.2
    },
    {
      "id": "abyssal_sight",
      "name": "Abyssal Sight",
      "level": 111,
      "luck": 0.4
    },
    {
      "id": "drowned_fortune",
      "name": "Drowned Fortune",
      "level": 121,
      "luck": 0.5
    }
  ],
  "bestiary": [
    {
      "kills": 500,
      "label": "I",
      "drop": 0.005,
      "walk": 0.001
    },
    {
      "kills": 1500,
      "label": "II",
      "drop": 0.01,
      "walk": 0.002
    },
    {
      "kills": 5000,
      "label": "III",
      "drop": 0.015,
      "walk": 0.003
    },
    {
      "kills": 15000,
      "label": "IV",
      "drop": 0.025,
      "walk": 0.005
    },
    {
      "kills": 50000,
      "label": "V",
      "drop": 0.04,
      "walk": 0.008
    },
    {
      "kills": 150000,
      "label": "VI",
      "drop": 0.06,
      "dmg": 0.02,
      "walk": 0.012
    },
    {
      "kills": 300000,
      "label": "VII",
      "drop": 0.08,
      "dmg": 0.04,
      "def": 0.02,
      "walk": 0.018
    },
    {
      "kills": 600000,
      "label": "VIII",
      "drop": 0.1,
      "dmg": 0.06,
      "def": 0.04,
      "walk": 0.028
    },
    {
      "kills": 1200000,
      "label": "IX",
      "drop": 0.13,
      "dmg": 0.08,
      "def": 0.06,
      "walk": 0.042
    },
    {
      "kills": 2500000,
      "label": "X",
      "drop": 0.16,
      "dmg": 0.1,
      "def": 0.08,
      "walk": 0.06
    }
  ]
};
if(typeof module !== "undefined") module.exports = EventData;
