/* Group exact potion equivalents without changing saved names or effect rules. */
(() => {
 const P=XPPrototype,R=CharacterProfile.R,$=id=>document.getElementById(id),tiles=new Map();
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const art=name=>name==='None'?'<span>−</span>':R.itemIcon(name,32).replaceAll('src="Assets/','src="combat_simulator/Assets/');
 for(const [id,kind,title]of [['gatheringPotion','gatheringPotions','Gathering Speed Potion'],['productionPotion','productionPotions','Production Speed Potion'],['xpPotion','xpPotions','Gathering XP Potion']]){
  const groups=[];for(const p of P.options[kind]){const signature=JSON.stringify([p.stat,p.value,p.flat||0,p.duration]),old=groups.find(g=>g.signature===signature);if(old)old.aliases.push(p.name);else groups.push({...p,signature,aliases:[]});}
  const select=$(id),label=select.closest('label'),button=document.createElement('button');button.type='button';button.className='companion-choice potion-choice';button.id='choose-'+id;button.setAttribute('aria-haspopup','dialog');select.hidden=true;label.firstChild.textContent='';label.append(button);tiles.set(id,{groups,select,button,title});button.addEventListener('click',()=>{slot=id;$('potion-title').textContent='Choose '+title;$('potion-search').value='';choices();dialog.showModal();$('potion-search').focus();});
 }
 const dialog=document.createElement('dialog');dialog.id='potion-picker';dialog.setAttribute('aria-labelledby','potion-title');dialog.innerHTML='<div class="picker-heading"><h2 id="potion-title"></h2><button type="button" id="potion-close" aria-label="Close Potion Picker">×</button></div><input type="search" id="potion-search" aria-label="Search potions" placeholder="Search regular or event names…"><p class="muted">Identical effects and minutes share one entry. Event versions with different stats remain separate.</p><div id="potion-choices" class="gear-choices"></div>';document.body.append(dialog);let slot;
 function refresh(){for(const {groups,select,button,title}of tiles.values()){const p=groups.find(g=>g.name===select.value||g.aliases.includes(select.value));button.innerHTML=art(p?.name||'None')+`<span><small>${title}</small><b>${esc(p?.name||'None')}</b>${p?.value?`<small>+${(p.value*100).toLocaleString('en-GB')}% · ${Number(p.duration/60000).toLocaleString('en-GB')} minutes per dose</small>`:''}</span>`;}for(const id of ['gatheringMinutes','productionMinutes','xpMinutes'])$(id).disabled=$('infinitePotions').checked;for(const id of ['xpCandyCount','speedCandyCount'])$(id).disabled=$('infiniteCandies').checked;}
 function choices(){const {groups,select}=tiles.get(slot),q=$('potion-search').value.toLowerCase();$('potion-choices').innerHTML=groups.filter(p=>(p.name+' '+p.aliases.join(' ')).toLowerCase().includes(q)).map(p=>`<button type="button" class="gear-choice" data-potion="${esc(p.name)}" aria-pressed="${p.name===select.value||p.aliases.includes(select.value)}">${art(p.name)}<span><b>${esc(p.name)}</b><small>${p.value?'+'+(p.value*100).toLocaleString('en-GB')+'% · '+Number(p.duration/60000).toLocaleString('en-GB')+' minutes per dose':'No potion'}</small>${p.aliases.length?`<small>Also: ${esc(p.aliases.join(', '))}</small>`:''}</span></button>`).join('')||'<p>No matching potions.</p>';}
 $('potion-search').addEventListener('input',choices);$('potion-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>tiles.get(slot)?.button.focus());$('potion-choices').addEventListener('click',e=>{const b=e.target.closest('[data-potion]');if(!b)return;const select=tiles.get(slot).select;select.value=b.dataset.potion;select.dispatchEvent(new Event('input',{bubbles:true}));dialog.close();refresh();});
 $('planner').addEventListener('input',refresh);document.addEventListener('xp-profile-context',refresh);document.addEventListener('xp-result',refresh);refresh();
})();
